# Generated by Django 5.2.8 on 2025-11-07 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('market_type', models.CharField(choices=[('spot', 'Spot'), ('future', 'Futures')], max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['symbol',],
            },
        ),
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('minutes', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['minutes'],
            },
        ),
        migrations.CreateModel(
            name='PairTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trackings', to='markets.marketpair')),
                ('timeframe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trackings', to='markets.timeframe')),
            ],
            options={
                'verbose_name': 'Pair Tracking',
                'verbose_name_plural': 'Pairs Tracking',
                'ordering': ['pair', 'timeframe'],
                'unique_together': {('pair', 'timeframe')},
            },
        ),
    ]
