# Generated by Django 5.2.8 on 2025-11-08 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketpair',
            name='market_type',
        ),
    ]
