# Generated by Django 5.2.8 on 2025-11-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0001_initial'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candle',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='candle',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='candle',
            index=models.Index(fields=['pair_tracking', 'timestamp'], name='candles_can_pair_tr_14b111_idx'),
        ),
        migrations.AddIndex(
            model_name='candle',
            index=models.Index(fields=['timestamp'], name='candles_can_timesta_939008_idx'),
        ),
        migrations.AddConstraint(
            model_name='candle',
            constraint=models.UniqueConstraint(fields=('pair_tracking', 'timestamp'), name='unique_candle_per_pair_time'),
        ),
    ]
