# Generated by Django 5.2.8 on 2025-11-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candles', '0002_alter_candle_unique_together_alter_candle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='timestamp_unix',
            field=models.BigIntegerField(default=0),
        ),
    ]
