# Generated by Django 5.2.8 on 2025-11-17 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0002_remove_marketpair_market_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategie', models.CharField(choices=[], max_length=50)),
                ('initial_balance', models.DecimalField(decimal_places=8, default=1000.0, max_digits=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('parameters', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.pairtracking')),
            ],
        ),
    ]
