# Generated by Django 5.2.8 on 2025-11-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtesting',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='backtesting',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='backtesting',
            name='status',
        ),
        migrations.AddField(
            model_name='backtesting',
            name='days_back',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='backtesting',
            name='strategie',
            field=models.CharField(max_length=50),
        ),
    ]
